spring:
  application:
    name: inventory-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          timeZone: UTC

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    drop-first: false  
    default-schema: inventory_service
    liquibase-schema: inventory_service
    contexts: dev,prod  
    label-filter: v1.0.0      
    parameters:
      appName: inventory-service
      appVersion: 1.0.0


server: 
  port: 8082
