openapi: 3.0.3
info:
  title: Inventory Service API
  description: This is the REST API for Inventory Service
  version: v0.0.1
  license:
    name: Apache 2.0
externalDocs:
  description: You can refer to the Inventory Service Wiki Documentation
  url: https://inventory-service-dummy-url.com/docs
servers:
  - url: http://localhost:8082
    description: Local development server
paths:
  /api/inventory:
    get:
      summary: Check inventory status
      description: Check if a product is in stock and has sufficient quantity
      operationId: checkInventory
      parameters:
        - name: skuCode
          in: query
          description: The product SKU code
          required: true
          schema:
            type: string
        - name: quantity
          in: query
          description: The requested quantity
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Inventory status checked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/inventory/create:
    post:
      summary: Create new inventory item
      description: Add a new product to inventory
      operationId: createInventory
      requestBody:
        description: Inventory item to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryRequest'
      responses:
        '201':
          description: Inventory item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    InventoryRequest:
      type: object
      required:
        - skuCode
        - quantity
      properties:
        skuCode:
          type: string
          example: "IPHONE13-128"
        quantity:
          type: integer
          format: int32
          example: 10
    InventoryResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        skuCode:
          type: string
          example: "IPHONE13-128"
        quantity:
          type: integer
          format: int32
          example: 10
        isInStock:
          type: boolean
          example: true
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2023-05-20T14:30:15.123Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "Product with Skucode: IPHONE13-128 not found in inventory"
        path:
          type: string
          example: "/api/inventory"
